language: python

services:
  - docker

before_install:
  - docker build -t kreeher/chives .
  - docker ps -a
  - docker run kreeher/chives


# todo: add tests and require pass
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master