language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
services:
  - docker

before_install:
  - docker build -t kreeher/chives .
  - docker ps -a

# command to install dependencies
install: "make"

# todo: add tests and require pass
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master