language: python

services:
  - docker

before_install:
  - docker build -t kreeher/chives .
  - docker ps -a

# command to install dependencies
install: "make"

# todo: add tests and require pass
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master