openapi: 3.0.0
# Added by API Auto Mocking Plugin
servers:
  - description: chives archival application api, activityPub compliant. 
    url: https://virtserver.swaggerhub.com/klreeher/chive/1.0.0
info:
  description: chives is a federated archive application
  version: "0.1.0"
  title: chives
  contact:
    email: kate@madecunningly.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers

paths:
  /users:
    get:
      summary: get information about a user 
      description: |
        by passing in an id or username, you can get information/profile of a specific user
      parameters:
        - in: query
          name: username
          schema:
            type: string
            minimum: 0
            maximum: 100
      responses:
       '200':
        description: search results matching criteria
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/User'
        '400':
          description: bad input parameter
components:
  schemas:
    User:
      type: object
      required:
        - id 
        - name 
        - emailAddress
      properties:
        id:
          type: string
          format: uuid
          example: f1ee-6c54-4b01-90e6d290-d701748f0851
        name:
          type: string
          example: madecunningly
        followers:
          type: string
        preferedUsername:
          type: string
        icon:
          type: string
          format: url
          example: 'https://kenzoishii.example.com/image/165987aklre4'
        summary:
          type: string

    Work:
      type: object
      required:
        - id
        - title
        - creatorID
        - content
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        user:
           $ref: '#/components/schemas/User'
        attachments:
          type: object
        source:
          type: object
        contents:
          type: string

    