# Generated by Django 2.2.2 on 2019-06-07 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('fandom', models.CharField(blank=True, default='', max_length=100)),
                ('tags', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='CollectionWork',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.Work')),
            ],
            bases=('works.work',),
        ),
        migrations.CreateModel(
            name='MediaWork',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.Work')),
                ('contents', models.FileField(upload_to='')),
            ],
            bases=('works.work',),
        ),
        migrations.CreateModel(
            name='TextWork',
            fields=[
                ('work_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.Work')),
                ('contents', models.CharField(blank=True, default='', max_length=100)),
            ],
            bases=('works.work',),
        ),
        migrations.CreateModel(
            name='AudioWork',
            fields=[
                ('mediawork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.MediaWork')),
                ('duration', models.DurationField()),
            ],
            bases=('works.mediawork',),
        ),
        migrations.CreateModel(
            name='ImageWork',
            fields=[
                ('mediawork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.MediaWork')),
                ('boo', models.CharField(blank=True, default='', max_length=100)),
            ],
            bases=('works.mediawork',),
        ),
        migrations.CreateModel(
            name='VideoWork',
            fields=[
                ('mediawork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='works.MediaWork')),
                ('duration', models.DurationField()),
                ('media', models.FileField(upload_to='')),
            ],
            bases=('works.mediawork',),
        ),
    ]
